### PR TITLE
feat: make payload example collapsible

### PR DESCRIPTION
**Pull request by WaleedAshraf**
Possible fix for #23 

I need help from someone.

Kapture 2020-05-22 at 14 22 20

### CODE REVIEW

**Comment by derberg** [comment]
@WaleedAshraf what help you need? I like how it is done in ReDoc

**Comment by derberg** [comment]
@WaleedAshraf there's also a duplicate issue here https://github.com/asyncapi/html-template/issues/19#issuecomment-620811026 with a good example of a big payload

**Comment by WaleedAshraf** [comment]
The way it is done in reDoc is too much work for me to do. I couldn't understand how they do it in the back.

This fix only solves the problem by making an example collapsable. We can later improve it to make it like how redoc has done it. 

Help needed: right now, it's showing both examples (headers + payload) in one view, it should be separate in two views and both should be collapsable. This is the point where my CSS skills ends.

**Comment by derberg** [comment]
@WaleedAshraf ok, I get ya, current `>` looks strange and is not that visible, reDoc clearly says Expand/Collaps so it would make more sense to have it clear on our side to, so instead the chevron icon I would suggest a clickable label Expand Example that once clicked, changes to Collapse Example. Or have a text/link and a chevron :) 

Regarding problem that header is visible in payload, and the other way around as well.
It is because you no longer use classes like `payload-examples mt-4` and `headers-examples mt-4`
 
Screenshot 2020-05-26 at 12 09 13

**Comment by WaleedAshraf** [comment]
redDoc have ExpandAll/CollapseAll because you can expand individual object.

In our case, we don't have that option.
Also, we use the only chevron all over the place. In schema, payload etc.

Shouldn't we keep it consistent?

**Comment by derberg** [comment]
good point about consistency, but then should instead of
Screenshot 2020-05-26 at 16 13 41

be something we already have, but with examples
Screenshot 2020-05-26 at 16 13 50

chevron is not that bad, but for the given background the color should be different, white?

**Comment by fmvilas** [comment]
IMO chevron is good (only needs to be white for contrast reasons, as Lukasz pointed out) but it's really weird there's no text along with it so I'd add something like `Example #0 >`.

**Comment by WaleedAshraf** [comment]
@fmvilas Yes, I'll the message name also with example so that examples don't mix up.

**Comment by WaleedAshraf** [comment]
@fmvilas @derberg how is this.

Kapture 2020-05-27 at 12 26 02

**Comment by derberg** [comment]
@WaleedAshraf message name is useful in case there are multiple messages at a channel, makes sense. What @fmvilas meant is that it is weird that the chevron is there alone, with no label. As I wrote here https://github.com/asyncapi/html-template/pull/34#issuecomment-634053761, maybe instead of those Payload and Header buttons, there should be just:
```
Examples

lightMeasured
Payload >
Headers >

turnOnOff
Payload >
Headers >
```
buttons look nice but using them looks cumbersome, advantage of my proposal is that you can expand both, payload and headers and see both at the same time

**Comment by WaleedAshraf** [comment]
@derberg 
Kapture 2020-05-27 at 13 52 31

**Comment by derberg** [comment]
@WaleedAshraf I'm in with my whole ❤️ 

would be awesome to see how it works with very large example.
@naderafshari could you check it with your spec documents? you can quickly test it with latest generator `0.50.1` and instead of using `@asyncapi/html-template` just put `https://github.com/asyncapi/html-template#issue-23-fix`

**Comment by WaleedAshraf** [comment]
need to apply few more fixes... in progress...

**Comment by WaleedAshraf** [comment]
@derberg ready for testing

Kapture 2020-05-27 at 16 04 04

**Comment by derberg** [comment]
@WaleedAshraf I checked against this https://github.com/metricq/metricq-rpc-docs/blob/master/manager.asyncapi.yaml that uses oneOf and there is some weird behavior

Screenshot 2020-05-28 at 10 19 19


Also, I believe that the Headers button should not be visible if there are no headers. I know that in current version it is grayed out and you left it like this, but in your new version there is also chevron, that you can still click to expand and collapse, even if headers are not there.  I hope you know what I mean 😄 so in the version you work on I vote for not having headers at all if they are not present

**Comment by WaleedAshraf** [comment]
https://github.com/metricq/metricq-rpc-docs/blob/master/manager.asyncapi.yaml 
This is working fine for me.
Check now, payload and headers button is hidden when not available.

Kapture 2020-05-28 at 10 34 36

**Comment by derberg** [comment]
@WaleedAshraf lgtm, I bet people will request a button to expand/collapse all examples with one click.

**Comment by WaleedAshraf** [comment]
they are welcome to open a pr. ;)

**Comment by derberg** [comment]
@all-contributors please add @WaleedAshraf for code, bug

**Pull request merged**
