### PR TITLE
feat: add option to override react config.

### PR DESCRIPTION
**Pull request by btimby**
I have updated `README.md`, I am testing this change locally right now. I will follow up with results shortly.

**Description**

- Adds an option for `html-template` to define react config.
- Can be used to disable sidebar.

**Related issue(s)**

https://github.com/asyncapi/html-template/issues/253

### CODE REVIEW

**Comment by btimby** [comment]
I added a unit test and manually verified that the sidebar is successfully removed.

**Comment by btimby** [comment]
This should be good to go. I checked how github renders the Markdown and I am happy with these changes.

**Review by magicmatatjahu — CHANGES_REQUESTED** [review]
@btimby Hello! Sorry for that late review 😅  I didn't notice that you created that (probably I missed this PR in notifications on Github, sometimes I get 50 a day)... really sorry.

I added some suggestions, great work btw and thanks for contribution :)

**Comment by magicmatatjahu** [comment]
@btimby Hi. Would you like to continue working on this PR in near future? :)

**Comment by magicmatatjahu** [comment]
@btimby That PR is still valid?

**Comment by magicmatatjahu** [comment]
Handled by https://github.com/asyncapi/html-template/pull/363 @btimby Thanks for contribution! In https://github.com/asyncapi/html-template/pull/363 we used your base code.

**Pull request closed without merging**
