### PR TITLE
fix: support node 12.2.0 when using singleFile parameter

### LINKED ISSUE #78: Creating Templates with Single File Parameter causes Error
#### Describe the bug
When using the single file parameter an error is thrown.

#### How to Reproduce
```{bash}
ag "schemas/school-events.yaml" @asyncapi/html-template --output "docs/school-events/" -p singleFile=true --force-write
```
```{bash}
Something went wrong:
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received { recursive: true }
    at makeCallback (fs.js:133:11)
    at Object.rmdir (fs.js:675:14)
    at generate:after (/usr/local/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/html-template/hooks/01_removeNotRelevantParts.js:21:16)
    at /usr/local/lib/node_modules/@asyncapi/generator/lib/generator.js:756:20
    at Array.map (<anonymous>)
    at Generator.launchHook (/usr/local/lib/node_modules/@asyncapi/generator/lib/generator.js:754:43)
    at Generator.generate (/usr/local/lib/node_modules/@asyncapi/generator/lib/generator.js:188:16)
    at async /usr/local/lib/node_modules/@asyncapi/generator/cli.js:123:9
```
### Version Used
- npm@6.14.8
- node@12.2.0
- asyncapi/generator@v1.0.0-rc.11

#### Expected behavior
The templates are generated correctly.

### PR DESCRIPTION
**Pull request by bufutda**
**Description**
Pulls in `rimraf` module which is a stable recursive directory delete that can replace `fs.rmdir` until it becomes stable.

**Related issue(s)**
Resolves #78

### CODE REVIEW

**Comment by derberg** [comment]
@bufutda thanks a lot for the contribution. In case you would like to pick more issues for the Hacktoberfest, have a look at https://www.asyncapi.com/blog/hacktoberfest-2020 and the google sheet we link there, where we maintain all the issues for the event

**Review by derberg — APPROVED** [review]
lgtm

**Comment by derberg** [comment]
@bufutda would you mind sharing with me how did you find out about AsyncAPI and this issue? we made some effort into Hacktoberfest and want to identify what efforts were the best for contributors and how they learned about us, so next Hacktoberfest is even better

**Comment by bufutda** [comment]
@derberg From the project-sharing channel in the Discord.

**Comment by derberg** [comment]
@bufutda thanks a lot. Fyi I gave you a shout out in our status blog post https://www.asyncapi.com/blog/status-update-43-20#change-default-name-of-html-file

**Pull request merged**
