### PR TITLE
docs: update README.md logo banner #331

### LINKED ISSUE #331: Update README with new logo banner
#### Reason/Context
This is to replace the old AsyncAPI logo in this repo's README with the banner attached below that represents the new branding.

**Here are a few guidelines for this change as well:**
1. Make sure you are using [Markdown syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) only
2. Be sure to remove the old logo as well as the old title of the repo as this image will replace both elements
3. Make sure you link this image to the website: `https://www.asyncapi.com`
4. If there is any description text below the repo title, let's make it left-aligned if it isn't already, so as to match the left-alignment of the content in the new banner image

**Download the image file:**
[github-repobanner-htmltemp.png.zip](https://github.com/asyncapi/html-template/files/8233311/github-repobanner-htmltemp.png.zip)

------

#### Banner preview
_Please note that this is only a preview of the image, the contributor should download and use the above zip file_ 

github-repobanner-htmltemp

### PR DESCRIPTION
**Pull request by raphaelletseng**
**Description**

- Update the README.md logo banner

**Related issue(s)**
Resolves #331

### CODE REVIEW

**Review by derberg — APPROVED** [review]
Thanks!

@mcturco do you want to approve these PRs too before we merge, you know to make sure all is good. Even though you know design is my passion, right? 😆

**Comment by mcturco** [comment]
@derberg Hahaha 😆 

Thank you, @raphaelletseng for this PR! I see that there was some HTML used in this README prior to the changes made here (and some of the other READMEs in the org for that matter), so I was just wondering if it made sense to replace the HTML with Markdown syntax? Or at least for this PR we add in the logo in markdown. Up to @derberg though really!

From a visual standpoint, it looks good to me!!

**Comment by raphaelletseng** [comment]
Hi, switched to just markdown, sorry about that!

**Comment by mcturco** [comment]
> Hi, switched to just markdown, sorry about that!

@raphaelletseng no worries, thank you! One more note: I think it would be helpful for accessibility if we make the alt text for the image `AsyncAPI HTML Template` so that it reads exactly the content that is in the image.

After that I think we are all set!

**Review by mcturco — APPROVED** [review]
Perfect!!! Thank you so much 🚢

**Review by magicmatatjahu — APPROVED** [review]
@raphaelletseng Thanks for contribution!

**Pull request merged**
