### PR TITLE
refactor: Remove unnecessary semicolons from filters

### LINKED ISSUE #70: Remove unnecessary semicolons from filters
Remove unnecessary semicolons:
- https://github.com/asyncapi/html-template/blob/master/filters/all.js#L64
- https://github.com/asyncapi/html-template/blob/master/filters/all.js#L105﻿

### PR DESCRIPTION
**Pull request by C-Zekeri**
**Description**
- Removed unnecessary semicolons.

**Related issue(s)**
Fixes #70

### CODE REVIEW

**Review by derberg — APPROVED** [review]
Thank you 🙇

**Comment by derberg** [comment]
@C-Zekeri would you mind sharing with me how did you find out about AsyncAPI and this issue? we made some effort into Hacktoberfest and want to identify what efforts were the best for contributors and how they learned about us, so next Hacktoberfest is even better

**Comment by C-Zekeri** [comment]
Hello @derberg. I found out about AsyncAPI from the HacktoberFest Discord channel, and I discovered this issue from the Google sheet.

**Comment by derberg** [comment]
@C-Zekeri thanks for the prompt answer. Looks like Discord is the best place so far

**Pull request merged**
