### PR TITLE
fix: rendering of list items in markdown and bold

### PR DESCRIPTION
**Pull request by dweber019**
**Description**
- Fix list styling for ol and ul
- Fix bold styling

**Related issue(s)**
- https://github.com/asyncapi/html-template/issues/162
- https://github.com/asyncapi/html-template/issues/142

### CODE REVIEW

**Comment by dweber019** [comment]
@derberg could you review the PR?

**Comment by derberg** [comment]
@dweber019 can you provide a screenshot of what it looks like before, how now with your PR, and the source used to display. I understood that you want to fix numbered lists but I tested you PR and still numbers show as bullets, so just want to confirm what is the expectation

**Comment by dweber019** [comment]
Here the yaml used
```yaml
asyncapi: '2.0.0'

externalDocs:
  description: Find more info here
  url: https://www.asyncapi.com

info:
  title: Dummy example with all spec features included
  version: '0.0.1'
  description: |
    - test
    - test 2
    - test 3

    1. test
    2. test 2
    3. test 3

    **bold**
```

Here before PR: https://ibb.co/Dp6Dmfn
and now: https://ibb.co/7Sdspr0

**Comment by derberg** [comment]
@dweber019 this is what I see after using your version

Screenshot 2021-03-30 at 10 31 02

make sure when running generation locally during development to pass `--install` flag to make sure that not cache is used, also validate with `--debug` what template from what location is used.

**Comment by dweber019** [comment]
Did you run `npm run generate:assets`?
As far as I understood the command `npm run generate:assets` is not part of the PR as seen in https://github.com/asyncapi/html-template/commit/e7e6629f61af0d289ee129584376d19010ad947f. It's part of the chore(release) bot right? https://github.com/asyncapi/html-template/commit/df9c9c75be996761b0440e4bdc8c905a90d82f82

**Comment by derberg** [comment]
🤦🏼 you are right, I completely forgot about it, we need to more it to hooks one day to ease development

**Review by derberg — APPROVED** [review]

**Comment by derberg** [comment]
@all-contributors please add @dweber019 for code

**Comment by dweber019** [comment]
@derberg thanks and no worries.

**Comment by derberg** [comment]
@dweber019 follow [this](https://github.com/asyncapi/playground/pulls) PR if you want to know when the fix will be on the playground. Once it is merged, Fran will push it right after

**Pull request merged**
