### PR TITLE
feat: add version parameter to allow version override

### LINKED ISSUE #107: Add a param to allow version override
#### Reason/Context

In a CI/CD context, generated doc must be fit with the current project version. To achieve this today, we need to use external workaround to change the spec version on the fly.

It will be nice to have a new param `version` to allow scripting and dynamically change the generated version of HTML template

#### Description
Please try answering few of those questions
- What changes have to be introduced?

Add a new `version` param to allow executing ` ag asyncapi.yaml @asyncapi/html-template  -p version=1.0.0`
- Will this be a breaking change?

No

- How could it be implemented/designed?

Simply add a `version` param which override the `version` attribute in the specification

### PR DESCRIPTION
**Pull request by M3lkior**
Close #107

### CODE REVIEW

**Review by derberg — COMMENTED** [review]
@M3lkior hey, please just update descriptions as suggested in the markdown-template

**Comment by M3lkior** [comment]
> @M3lkior hey, please just update descriptions as suggested in the markdown-template

Done

**Review by derberg — APPROVED** [review]
@M3lkior thanks a lot 🙏🏼 

just a hint for future contributions, please do not force push as it makes the review process much harder as the reviewer cannot easily see what was added after the review, and has to review entire PR once again.
You do not have to worry about the git history as we anyway always squash and merge at the end.

**Comment by M3lkior** [comment]
> @M3lkior thanks a lot 🙏🏼
> 
> just a hint for future contributions, please do not force push as it makes the review process much harder as the reviewer cannot easily see what was added after the review, and has to review entire PR once again.
> You do not have to worry about the git history as we anyway always squash and merge at the end.

ok @derberg :)

**Pull request merged**
