### PR TITLE
feat: Add singleFile param to generate everything in one index.html

### LINKED ISSUE #61: Add parameter singleFile
Motivation: publicate asyncapi into services that accept only single documents.

Add parameter **singleFile** to get html with scripts and styles in one file.

```
"singleFile": {
        "description": "If set this parameter to true generate single html file with scripts and styles inside",
        "required": false,
        "default": false
      }
```
Make something like this in index.html:

```
  {% if params.singleFile %}
    <style type="text/css">
    {% include "template/css/tailwind.min.css" %}
    </style>
    <style type="text/css">
    {% include "template/css/atom-one-dark.min.css" %}
    </style>
    <style type="text/css">
    {% include "template/css/main.css" %}
    </style>
  {% else %}
  <link href="css/tailwind.min.css" rel="stylesheet">
  <link rel="stylesheet" href="css/atom-one-dark.min.css" />
  <link rel="stylesheet" href="css/main.css" />
  {% endif %}
```
```
  {% if params.singleFile %}
    <script defer type="text/javascript">
    {% include "template/js/highlight.min.js" %}

    {% include "template/js/main.js" %}
    </script>
  {% else %}
  <script src="js/highlight.min.js" type="application/javascript"></script>
  <script src="js/main.js" type="application/javascript"></script>
  {% endif %}
```

### PR DESCRIPTION
**Pull request by GordeevArt**
Add singleFile param to output all in one html file

Resolves #61

### CODE REVIEW

**Comment by derberg** [comment]
@GordeevArt Thanks a lot for this PR! Could you explain why there are changes to `template/js/highlight.min.js `, did you do some updates to it?

**Comment by GordeevArt** [comment]
@derberg I replace `"</script>"` with `"<" + "/script>"` as workaround for escaping in html. It is not a good way. If you know better way please let me know.

**Comment by derberg** [comment]
@GordeevArt sorry but could you somehow show to me what happens if you do not have this change?

If we change it directly in `highlight.min.js` the risk is that later, when someone updates it with the latest https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.2.0/build/highlight.min.js, your change will easily get lost

**Comment by GordeevArt** [comment]
@derberg error in browser's console, not clickable example's buttons and something terrible with component's messages.

image

image

image

**Comment by derberg** [comment]
@GordeevArt Thanks for your explanation. I just checked and looks like with latest [highlight.js](https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.2.0/build/highlight.min.js,) the problem is not there so please just update the entire file with the latest one

**Comment by GordeevArt** [comment]
@derberg yes. There is no problem with the latest versuib of [highlight.js](https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.2.0/build/highlight.min.js)

**Comment by derberg** [comment]
@GordeevArt I tested it locally, works like a charm. Thanks a lot for a great contribution!

**Comment by derberg** [comment]
@GordeevArt feel free to join us on our slack https://www.asyncapi.com/slack-invite/

**Pull request merged**
