### PR TITLE
fix: lock react components version

### LINKED ISSUE #438: TypeError: message.id is not a function
#### Describe the bug
TypeError: message.id is not a function

#### How to Reproduce

Use `asyncapi.yml` with the following content

```yml
asyncapi: '2.6.0'
info:
  title: Account Service
  version: 1.0.0
  description: This service is in charge of processing user signups
channels:
  user/signedup:
    subscribe:
      message:
        $ref: '#/components/messages/UserSignedUp'
components:
  messages:
    UserSignedUp:
      payload:
        type: object
        properties:
          displayName:
            type: string
            description: Name of the user
          email:
            type: string
            format: email
            description: Email of the user

```
run
```
npm install  @asyncapi/generator
ag asyncapi.yml @asyncapi/html-template -o out

Something went wrong:
TypeError: message.id is not a function
    at /Users/z0024p1y/node_modules/@asyncapi/generator/node_modules/@asyncapi/react-component/src/containers/Sidebar/Sidebar.tsx:51:64
    at Array.map (<anonymous>)
    at Sidebar (/Users/z0024p1y/node_modules/@asyncapi/generator/node_modules/@asyncapi/react-component/src/containers/Sidebar/Sidebar.tsx:44:35)
    at processChild (/Users/z0024p1y/node_modules/@asyncapi/generator/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/Users/z0024p1y/node_modules/@asyncapi/generator/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/Users/z0024p1y/node_modules/@asyncapi/generator/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/Users/z0024p1y/node_modules/@asyncapi/generator/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at Object.renderToString (/Users/z0024p1y/node_modules/@asyncapi/generator/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at Context.renderSpec (/Users/z0024p1y/node_modules/@asyncapi/generator/node_modules/@asyncapi/html-template/filters/all.js:165:25)
    at eval (eval at _compile (/Users/z0024p1y/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:527:18), <anonymous>:38:97)
    at Context.generateBase64Favicon (/Users/z0024p1y/node_modules/@asyncapi/generator/node_modules/@asyncapi/html-template/filters/all.js:105:12)
    at Template.root [as rootRenderFunc] (eval at _compile (/Users/z0024p1y/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:527:18), <anonymous>:21:40)
    at Template.render (/Users/z0024p1y/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:454:10)
    at Environment.renderString (/Users/z0024p1y/node_modules/@asyncapi/generator/node_modules/nunjucks/src/environment.js:313:17)
    at /Users/z0024p1y/node_modules/@asyncapi/generator/lib/renderer/nunjucks.js:32:14
    at new Promise (<anonymous>)
```

#### Expected behavior

no error

I use node  v18.16.0 and ag version 1.10.14, but this occurs since yesterday also on other versions!

### PR DESCRIPTION
**Pull request by jonaslagoni**
**Description**
This PR locks the react components to not use the `1.0.0-next.48` version which contains breaking changes for this library.

**Related issue(s)**
Fixes #438

### CODE REVIEW

**Review by fmvilas — DISMISSED** [review]

**Comment by jonaslagoni** [comment]
blocked by https://github.com/asyncapi/html-template/pull/440

**Comment by derberg** [comment]
@jonaslagoni but this is not going to work. I assume you want to make sure automated bump will not work and upgrade? it do not understand existence of `^`, I mean the action responsible for the bump.

anyway, tests will not let the bump go through -> see https://github.com/asyncapi/html-template/pull/437

so what you're trying to solve here? stop having automated PRs like https://github.com/asyncapi/html-template/pull/437 ?

**Comment by jonaslagoni** [comment]
@derberg in this repo bumps will still happen yes.

But it will make sure that people that install the library wont get the newest component library as in https://github.com/asyncapi/html-template/issues/438.

**Comment by derberg** [comment]
oh, ok, so not autobump related, thanks for clarification

**Review by derberg — APPROVED** [review]

**Pull request merged**
