### PR TITLE
feat: include `__transpiled` folder in the package

### PR DESCRIPTION
**Pull request by utnim2**
**Description**

- Include `__transpiled`  folder in publishing of the package 
- Have modified the `.npmignore` for including the transpiled folder

image

**Related issue(s)**
Resolves #575

### CODE REVIEW

**Comment by aeworxet** [comment]
https://github.com/orgs/asyncapi/teams/bounty_team

**Comment by aeworxet** [comment]
@asyncapi/bounty_team

**Review by derberg — APPROVED** [review]
tried on local `npm publish --dry-run` and all looks good

**Pull request merged**
